version: '3.8'
 
services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    #Sets  Envrionment Password
    environment:
      POSTGRES_PASSWORD: "${postgres_pass}"
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_DB: "${postgres_db}"
    #Port for Postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my_db_files
        target: /var/lib/postgresql/data
  #Adminer
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
 
volumes:
  my_db_files: